language: php
php:
  - 7.1
  - 7.2
  - 7.3

before_script:
  - composer install --no-interaction

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit

after_script:
  - php vendor/bin/coveralls